<MainScreen>:
    name: 'main'
    FloatLayout:
        size_hint: None, None

    DPEAButton:
        id: useless_button #todo fix this section (step 3)
        size: 100, 100
        text: "off" if test_button.state == "normal" else "on"
        x: root.width * 0.5
        y: root.height * 0.2
        color: 1, 0.3, 0.2, 1

    DPEAButton:
        id: test_button# todo: add counter
        text:"count:"
        size: 100, 100
        x: root.width * 0.75
        y: root.height * 0.5
        color: 0, 1, 0, 1
        #on_press:


    DPEAButton:
        id: on_button
        text: "off" if on_button.state == "normal" else "on"
        size: 100, 100
        x: root.width * 0.25
        y:root.height * 0.5
        color: 1, 0, 0, 1


    ImageButton:
        id: logo_image_button
        source: "../../pidev/kivy/images/DPEALogoTransparent.png"
        size: 100, 100
        x: root.width * 0.5
        y: root.height * 0.5
        on_press: root.pressed()