<MainScreen>:
    name: 'main'
    FloatLayout:
        size_hint: None, None

    DPEAButton:
        id: test_button
        text:"test"  #todo finish making on/off button
        size: 100, 100
        x: root.width * 0.75
        y: root.height * 0.5
        color: 0, 1, 0, 1
        on_press: root.pressed()

    DPEAButton:
        id: on_button
        text: "off" if on_button.state == "normal" else "on"
        size: 100, 100
        x: root.width * 0.25
        y:root.height * 0.5
        color: 1, 0, 0, 1


    ImageButton:
        id: logo_image_button
        source: "../../pidev/kivy/images/DPEALogoTransparent.png"
        size: 100, 100
        x: root.width * 0.5
        y: root.height * 0.5
        on_press: root.pressed()